# Generated by Django 4.2.5 on 2024-09-05 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("address", models.SlugField(max_length=255, unique=True)),
                ("meta", models.TextField(max_length=400)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, max_length=255, upload_to="blog/thumbnails_%Y/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("T", "Published"), ("F", "Draft")], max_length=1
                    ),
                ),
                ("read_time", models.SmallIntegerField()),
                ("views", models.IntegerField()),
                ("likes", models.IntegerField()),
                ("created_at", models.DateField()),
                ("last_modified", models.DateField(auto_now=True)),
                ("open_conv", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
