# Generated by Django 4.2.5 on 2024-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="open_conv",
            field=models.BooleanField(default=True, verbose_name="Open Converstaion"),
        ),
    ]
