# Generated by Django 4.2.5 on 2024-09-05 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0003_article_category_article_tags_blogcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="article",
            name="views",
        ),
        migrations.AddField(
            model_name="article",
            name="likes",
            field=models.ManyToManyField(
                related_name="viewed", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.ManyToManyField(
                related_name="liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
