# Generated by Django 4.2.5 on 2024-09-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_article_likes_remove_article_views_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ("last_modified",)},
        ),
    ]
