# Generated by Django 4.2.5 on 2024-09-06 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mediastore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("value", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="DiscountGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("meta", models.TextField(blank=True, max_length=400)),
                ("amount", models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("address", models.SlugField(max_length=255, unique=True)),
                (
                    "thumbnail",
                    models.ImageField(max_length=500, upload_to="store/products/%Y-%m"),
                ),
                ("meta", models.TextField(max_length=400)),
                ("exist", models.BooleanField(default=False)),
                ("org_price", models.IntegerField(default=0)),
                ("discount", models.SmallIntegerField(default=0)),
                ("buyers", models.IntegerField(default=0)),
                ("details", models.ManyToManyField(to="store.detail")),
                (
                    "discount_group",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store.discountgroup",
                    ),
                ),
                ("images", models.ManyToManyField(to="mediastore.image")),
                ("videos", models.ManyToManyField(to="mediastore.video")),
            ],
        ),
        migrations.CreateModel(
            name="reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.SmallIntegerField(default=0)),
                ("comment", models.TextField(max_length=500)),
                ("show", models.BooleanField(default=False)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store.product",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
