# Generated by Django 4.2.5 on 2024-09-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_reviews_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("T", "Published"), ("F", "Draft")], default="F", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reviews",
                to="store.product",
            ),
        ),
    ]
