# Generated by Django 4.2.5 on 2024-09-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sort", "0001_initial"),
        ("store", "0003_product_status_alter_review_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Tags",
            field=models.ManyToManyField(blank=True, to="sort.tag"),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(blank=True, to="sort.category"),
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("products", models.ManyToManyField(blank=True, to="store.product")),
            ],
        ),
    ]
