# Generated by Django 4.2.16 on 2024-09-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediastore", "0001_initial"),
        ("store", "0004_product_tags_product_categories_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(blank=True, to="mediastore.image"),
        ),
        migrations.AlterField(
            model_name="product",
            name="videos",
            field=models.ManyToManyField(blank=True, to="mediastore.video"),
        ),
    ]
